package com.example.activities.api;

public class Recomendation {

	
//	   private Predicate createPredicate(boolean onlyInViewport, String titleContains) {
//	        //QSpatialEvent missing? Do a priming build aka "mvn install". 
//	        // QSpatialEvent is a helper class automatically generated by QueryDSL
//	        QSpatialEvent qspatialEvent = QSpatialEvent.spatialEvent;
//	        BooleanExpression intersection = null;
//	        BooleanExpression predicate = null;
//	        if (onlyInViewport) {
//	            Polygon polygon = toPolygon(map.getBounds());
//	            intersection = qspatialEvent.location.intersects(polygon);
//	        }
//	        BooleanExpression title = null;
//	        if (StringUtils.isNotBlank(titleContains)) {
//	            title = qspatialEvent.title.containsIgnoreCase(titleContains);
//	        }
//	        if (intersection != null && title != null) {
//	            predicate = title.and(intersection);
//	        } else if (intersection != null) {
//	            predicate = intersection;
//	        } else if (title != null) {
//	            predicate = title;
//	        }
//	        return predicate;
//	    }
//
//	    private Polygon toPolygon(Bounds bounds) {
//	        GeometryFactory factory = new GeometryFactory();
//	        double north = bounds.getNorthEastLat();
//	        double south = bounds.getSouthWestLat();
//	        double west = bounds.getSouthWestLon();
//	        double east = bounds.getNorthEastLon();
//	        Coordinate[] coords = new Coordinate[]{new Coordinate(east, north), new Coordinate(east, south),
//	            new Coordinate(west, south), new Coordinate(west, north), new Coordinate(east, north)};
//	        // GeoDb does not support LinerRing intersection, but polygon ?!
//	        LinearRing lr = factory.createLinearRing(coords);
//	        Polygon polygon = factory.createPolygon(lr, null);
//	        polygon.setSRID(4326);
//	        return polygon;
//	    }
	
}
